# 全局日志级别
LOG_LEVEL = "debug"
SERVER_HTTP_IP = "127.0.0.1"

LEAF_NAME="default"
LEAF_SNOWFLAKE_PORT= 2181
LEAF_SNOWFLAKE_ZK_ADDRESS="127.0.0.1"
LEAF_SNOWFLAKE_EN="en1"
LEAF_SNOWFLAKE_START_TIME="2010-11-04 09:42:54"
# log
LOG_FILTERS = ""
LOG_IGNORES = ""

# DB 配置，格式为 DB_${NAME}_DSN，内容参考
# https://github.com/go-sql-driver/mysql#dsn-data-source-name
# 必须设置 parseTime 选项
# 通过 ${NAME} 可以获取 DB 连接池
# 时区问题参考 https://www.jianshu.com/p/3f7fc9093db4

DB_DEFAULT_DSN = "root:root@tcp(127.0.0.1:3306)/leaf_go?parseTime=true&loc=Local&charset=utf8mb4&allowNativePasswords=true"
DB_DEFAULT_TABLE_PREFIX = ""
DB_DEFAULT_AUTO_CREATE_TABLE = true

# MC 配置，格式为 MC_${NAME}_HOSTS = "host1,host2"
# 通过 ${NAME} 可以获取 MC 连接池
MC_DEFAULT_HOSTS = "127.0.0.1:11211"
# 初始连接数
MC_DEFAULT_INIT_CONNS = 1
# 最大空闲连接数，设为峰值并发数
MC_DEFAULT_MAX_IDLE_CONNS = 2

# Redis 配置
 REDIS_DEFAULT_HOST = "127.0.0.1:6379"
# 初始连接数
REDIS_DEFAULT_INIT_CONNS = 1
# 最大连接数
REDIS_DEFAULT_MAX_CONNS = 2

OUTER_API_TIMEOUT = 60

[SENTINEL_RES_QPS]